# Generated by Django 3.1.5 on 2021-01-30 21:08

from django.db import migrations, models
import django.db.models.deletion
import tictactoe.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN', 'Incomplete'), ('WN', 'Win'), ('DR', 'Draw')], default='IN', max_length=2)),
                ('grid', models.JSONField(default=tictactoe.utils.empty_game_grid)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(choices=[('OS', 'Noughts'), ('XS', 'Crosses')], default='OS', max_length=2)),
                ('coord', models.JSONField(default=tictactoe.utils.default_coords)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tictactoe.game')),
            ],
        ),
    ]
