# Generated by Django 3.1.5 on 2021-01-30 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='move',
            old_name='coord',
            new_name='coords',
        ),
    ]
